version: 2.1
workflows:
  main:
    jobs:
      - run-action
jobs:
  run-action:
    machine:
      image: ubuntu-2004:202010-01
      # Docker layer caching seems to be enabled on GitHub Actions
      # docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Building Super Linter
          command: |
            CIRCLE_WORKING_DIRECTORY=$(eval "echo $CIRCLE_WORKING_DIRECTORY")
            cd $CIRCLE_WORKING_DIRECTORY/.github/workflows/
            git clone git@github.com:github/super-linter.git
            cd super-linter
            docker build . -t superlinter-$CIRCLE_SHA1
      - run:
          name: Run Super Linter
          command: |
            CIRCLE_WORKING_DIRECTORY=$(eval "echo $CIRCLE_WORKING_DIRECTORY")
            /usr/bin/docker run --name ghcriogithubsuperlinterv3_e188a9 --label cc4956 --workdir /github/workspace --rm -e VALIDATE_ALL_CODEBASE -e DEFAULT_BRANCH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/GH_Actions_on_CircleCI/GH_Actions_on_CircleCI":"/github/workspace" ghcr.io/github/super-linter:v3
      - run:
          name: Confirm
          command: echo "SuperLinter has been executed via CircleCI with Docker Layer Caching"