version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  run-action:
    machine:
      image: ubuntu-2004:202010-01
      # Docker layer caching seems to be enabled on GitHub Actions
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Building Super Linter
          command: |
            mkdir "$CIRCLE_WORKING_DIRECTORY/.github/workflows/superlinter"
            cd "$CIRCLE_WORKING_DIRECTORY/.github/workflows/superlinter"
            git clone git@github.com:github/super-linter.git
            docker build . -t superlinter-$CIRCLE_SHA1
      - run:
          name: Run Super Linter
          command: |
            docker run -e RUN_LOCAL=true -v $CIRCLE_WORKING_DIRECTORY superlinter-$CIRCLE_SHA1
      - run:
          name: Confirm
          command: echo "SuperLinter has been executed via CircleCI"