version: 2.1
workflows:
  main:
    jobs:
      - run-action
jobs:
  run-action:
    machine:
      image: ubuntu-2004:202010-01
      # Docker layer caching seems to be enabled on GitHub Actions
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Building Super Linter
          command: |
            CIRCLE_WORKING_DIRECTORY=$(eval "echo $CIRCLE_WORKING_DIRECTORY")
            cd $CIRCLE_WORKING_DIRECTORY/.github/workflows/
            git clone git@github.com:github/super-linter.git
            cd super-linter
            docker build . -t superlinter-$CIRCLE_SHA1
      - run:
          name: Run Super Linter
          command: |
            CIRCLE_WORKING_DIRECTORY=$(eval "echo $CIRCLE_WORKING_DIRECTORY")
            docker run -e RUN_LOCAL=true -v $CIRCLE_WORKING_DIRECTORY:/tmp/lint github/super-linter superlinter-$CIRCLE_SHA1
      - run:
          name: Confirm
          command: echo "SuperLinter has been executed via CircleCI with Docker Layer Caching"