version: 2.1
workflows:
  main:
    jobs:
      - run-action
jobs:
  run-action:
    machine:
      image: ubuntu-2004:202010-01
      # Docker layer caching seems to be enabled on GitHub Actions
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Building Super Linter
          command: |
            cd ~/project/.github/workflows/
            git clone git@github.com:github/super-linter.git
            cd super-linter
            docker build . -t superlinter-$CIRCLE_SHA1
      - run:
          name: Run Super Linter
          command: |
            docker run -e RUN_LOCAL=true -v ~/project superlinter-$CIRCLE_SHA1
      - run:
          name: Confirm
          command: echo "SuperLinter has been executed via CircleCI with Docker Layer Caching"